- hosts: worker
  become: yes
  tasks:
    - name: install deps for apt
      apt: name={{ item }} state=latest update_cache=true
      with_items:
        - python3-apt
        - python-apt

    - name: add php repository
      apt_repository:
        repo: deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main 


    - name: install nginx, php7, git
      apt: name={{ item }} state=latest force=true
      with_items:
        - nginx
        - git
        - unzip
        - php7.2
        - php7.2-cli
        - php7.2-dev
        - php7.2-sqlite3 
        - php7.2-gd
        - php7.2-curl 
        - php7.2-memcached
        - php7.2-imap 
        - php7.2-mysql 
        - php7.2-mbstring
        - php7.2-xml 
        - php7.2-zip 
        - php7.2-bcmath 
        - php7.2-soap
        - php7.2-readline
        - php7.2-fpm

    - name: download composer
      command: curl -sS https://getcomposer.org/installer -o composer-setup.php

    - name: install composer
      command: php composer-setup.php --install-dir=/usr/local/bin --filename=composer

    - name: clone and install project
      shell: |
        cd /var/www

        git clone https://github.com/udinIMM/Hackathon Hackaton
        cd Hackaton

        rm database/migrations/2018_04_21_175358_add_name_column_users.php

        cp .env.example .env

        php artisan key:generate

        sed -i "s/DB_HOST=/DB_HOST=10.151.36.194/g" .env
        sed -i "s/DB_DATABASE=/DB_DATABASE=regalq/g" .env
        sed -i "s/DB_USERNAME=/DB_USERNAME=regal/g" .env
        sed -i "s/DB_PASSWORD=/DB_PASSWORD=bolaubi/g" .env

        composer install

        php artisan migrate
        
        chown www-data:www-data -R .
        chmod 777 -R .

    - name: config nginx
      copy:
        src: /home/syukronrm/Kuliah/cloud/ansible/modul/nginx/default
        dest: /etc/nginx/sites-available/default

    - name: restart nginx
      service:
        name: nginx
        state: restarted
